schema_version = 1
minimum_dotflow_version = "0.1.0"

[repository]
branch = "master"
origin = "git@github.com:uvu1/dotflow.git"
mise_dir = "."

[profiles.linux-workstation]
platform = "linux"
add_environment = "linux"
[[profiles.linux-workstation.environments]]
mise_environment = "linux"

[profiles.wsl-workstation]
platform = "wsl"
add_environment = "linux"
[[profiles.wsl-workstation.environments]]
mise_environment = "linux"

[profiles.apple-silicon]
platform = "macos"
arch = "aarch64"
add_environment = "darwin"
[[profiles.apple-silicon.environments]]
mise_environment = "darwin"

[profiles.windows-workstation]
platform = "windows"
add_environment = "windows"
[[profiles.windows-workstation.environments]]
mise_environment = "windows"
[[profiles.windows-workstation.environments]]
mise_environment = "pwsh"
